name: docker-publish-latest
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/docker-publish-latest.yaml"
      - "Dockerfile"
jobs:
  call-base-docker-publish:
    uses: ./.github/workflows/base-docker-publish.yml
    secrets: inherit
    with:
      version: latest
